// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppMVC.Data;

namespace WebAppMVC.Migrations
{
    [DbContext(typeof(WebAppMVCContext))]
    [Migration("20210805214529_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppMVC.Models.Show", b =>
                {
                    b.Property<int>("showid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("appstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("releasedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("showname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("showid");

                    b.ToTable("Show");
                });
#pragma warning restore 612, 618
        }
    }
}
